cap program drop country_codes_reverse
	program def country_codes_reverse

	cap drop country_name
	
	gen country_name=""
		replace	country_name="Afghanistan" if country_iso3=="AFG"
		replace	country_name="Albania" if country_iso3=="ALB"
		replace	country_name="Algeria" if country_iso3=="DZA"
		replace	country_name="American Samoa" if country_iso3=="USAASM"
		replace	country_name="Andorra" if country_iso3=="AND"
		replace	country_name="Angola" if country_iso3=="AGO"
		replace	country_name="Anguilla" if country_iso3=="AIA"
		replace	country_name="Antigua and Barbuda" if country_iso3=="ATG"
		replace	country_name="Antarctica" if country_iso3=="ANT"
		replace	country_name="Argentina" if country_iso3=="ARG"
		replace	country_name="Armenia" if country_iso3=="ARM"
		replace	country_name="Aruba" if country_iso3=="ABW"
		replace	country_name="Australia" if country_iso3=="AUS"
		replace	country_name="Austria" if country_iso3=="AUT"
		replace	country_name="Azerbaijan" if country_iso3=="AZE"
		replace	country_name="Bahamas" if country_iso3=="BHS"
		replace	country_name="Bahrain" if country_iso3=="BHR"
		replace	country_name="Bangladesh" if country_iso3=="BGD"
		replace	country_name="Barbados" if country_iso3=="BRB"
		replace	country_name="Belarus" if country_iso3=="BLR"
		replace	country_name="Belgium" if country_iso3=="BEL"
		replace	country_name="Belize" if country_iso3=="BLZ"
		replace	country_name="Benin" if country_iso3=="BEN"
		replace	country_name="Bermuda" if country_iso3=="BMU"
		replace	country_name="Bhutan" if country_iso3=="BTN"
		replace	country_name="Bolivia" if country_iso3=="BOL"
		replace	country_name="Bosnia and Herzegovina" if country_iso3=="BIH"
		replace	country_name="Botswana" if country_iso3=="BWA"
		replace	country_name="Brazil" if country_iso3=="BRA"
		replace	country_name="British Virgin Islands" if country_iso3=="GBRVGB"
		replace	country_name="Brunei Darussalam" if country_iso3=="BRN"
		replace	country_name="Bulgaria" if country_iso3=="BGR"
		replace	country_name="Burkina Faso" if country_iso3=="BFA"
		replace	country_name="Burundi" if country_iso3=="BDI"
		replace	country_name="Cambodia" if country_iso3=="KHM"
		replace	country_name="Cameroon" if country_iso3=="CMR"
		replace	country_name="Canada" if country_iso3=="CAN"
		replace	country_name="Cape Verde" if country_iso3=="CPV"
		replace	country_name="Cayman Islands" if country_iso3=="CYM"
		replace	country_name="Central African Republic" if country_iso3=="CAF"
		replace	country_name="Chad" if country_iso3=="TCD"
		replace	country_name="Chile" if country_iso3=="CHL"
		replace	country_name="China" if country_iso3=="CHN"
		replace	country_name="Colombia" if country_iso3=="COL"
		replace	country_name="Comoros" if country_iso3=="COM"
		replace	country_name="Congo-Brazzaville" if country_iso3=="COG"
		replace	country_name="Cook Islands" if country_iso3=="COK"
		replace	country_name="Costa Rica" if country_iso3=="CRI"
		replace	country_name="Cote d'Ivoire" if country_iso3=="CIV"
		replace	country_name="Croatia" if country_iso3=="HRV"
		replace	country_name="Cuba" if country_iso3=="CUB"
		replace	country_name="Curaçao" if country_iso3=="CUW"
		replace	country_name="Cyprus" if country_iso3=="CYP"
		replace	country_name="Czech Republic" if country_iso3=="CZE"
		replace	country_name="Democratic Republic of Congo" if country_iso3=="COD"
		replace	country_name="Denmark" if country_iso3=="DNK"
		replace	country_name="Djibouti" if country_iso3=="DJI"
		replace	country_name="Dominica" if country_iso3=="DMA"
		replace	country_name="Dominican Republic" if country_iso3=="DOM"
		replace	country_name="Ecuador" if country_iso3=="ECU"
		replace	country_name="Egypt" if country_iso3=="EGY"
		replace	country_name="El Salvador" if country_iso3=="SLV"
		replace	country_name="Equatorial Guinea" if country_iso3=="GNQ"
		replace	country_name="Eritrea" if country_iso3=="ERI"
		replace country_name="Estonia" if country_iso3=="EST"
		replace	country_name="Ethiopia" if country_iso3=="ETH"
		replace	country_name="Faroe Islands" if country_iso3=="DNKFRO"
		replace	country_name="Falkland Islands" if country_iso3=="GBRFLK"
		replace	country_name="Fiji" if country_iso3=="FJI"
		replace	country_name="Finland" if country_iso3=="FIN"
		replace	country_name="France" if country_iso3=="FRA"
		replace	country_name="French Guiana" if country_iso3=="FRAGUF"
		replace	country_name="French Polynesia" if country_iso3=="FRAPYF"
		replace	country_name="Gabon" if country_iso3=="GAB"
		replace	country_name="Gambia" if country_iso3=="GMB"
		replace	country_name="Georgia" if country_iso3=="GEO"
		replace	country_name="Germany" if country_iso3=="DEU"
		replace	country_name="Ghana" if country_iso3=="GHA"
		replace	country_name="Gibraltar" if country_iso3=="GBRGIB"
		replace	country_name="United Kingdom" if country_iso3=="GBR"
		replace	country_name="Greece" if country_iso3=="GRC"
		replace	country_name="Greenland" if country_iso3=="DNKGRL"
		replace	country_name="Grenada" if country_iso3=="GRD"
		replace	country_name="Guadeloupe" if country_iso3=="FRAGLP"
		replace	country_name="Guam" if country_iso3=="USAGUM"
		replace	country_name="Guatemala" if country_iso3=="GTM"
		replace	country_name="Guernsey" if country_iso3=="GGY"
		replace	country_name="Guinea" if country_iso3=="GIN"
		replace	country_name="Guinea-Bissau" if country_iso3=="GNB"
		replace	country_name="Guyana" if country_iso3=="GUY"
		replace	country_name="Haiti" if country_iso3=="HTI"
		replace	country_name="Holy See" if country_iso3=="VAT"
		replace	country_name="Honduras" if country_iso3=="HND"
		replace	country_name="Hong Kong" if country_iso3=="HKG"
		replace	country_name="Hungary" if country_iso3=="HUN"
		replace	country_name="Iceland" if country_iso3=="ISL"
		replace	country_name="India" if country_iso3=="IND"
		replace	country_name="Indonesia" if country_iso3=="IDN"
		replace	country_name="Iran" if country_iso3=="IRN"
		replace	country_name="Iraq" if country_iso3=="IRQ"
		replace	country_name="Ireland" if country_iso3=="IRL"
		replace	country_name="Isle Of Man" if country_iso3=="GBRIMY"
		replace	country_name="Israel" if country_iso3=="ISR"
		replace	country_name="Italy" if country_iso3=="ITA"
		replace	country_name="Jamaica" if country_iso3=="JAM"
		replace	country_name="Japan" if country_iso3=="JPN"
		replace	country_name="Jordan" if country_iso3=="JOR"
		replace	country_name="Kazakhstan" if country_iso3=="KAZ"
		replace	country_name="Kenya" if country_iso3=="KEN"
		replace	country_name="Kiribati" if country_iso3=="KIR"
		replace	country_name="Kosovo" if country_iso3=="KSV"
		replace	country_name="Kyrgyzstan" if country_iso3=="KGZ"
		replace	country_name="Kuwait" if country_iso3=="KWT"
		replace	country_name="Laos" if country_iso3=="LAO"
		replace	country_name="Latvia" if country_iso3=="LVA"
		replace	country_name="Lebanon" if country_iso3=="LBN"
		replace	country_name="Lesotho" if country_iso3=="LSO"
		replace	country_name="Liberia" if country_iso3=="LBR"
		replace	country_name="Libya" if country_iso3=="LBY"
		replace	country_name="Liechtenstein" if country_iso3=="LIE"
		replace	country_name="Lithuania" if country_iso3=="LTU"
		replace	country_name="Luxembourg" if country_iso3=="LUX"
		replace	country_name="Macedonia" if country_iso3=="MKD"
		replace	country_name="Macao" if country_iso3=="MAC"
		replace	country_name="Madagascar" if country_iso3=="MDG"
		replace	country_name="Malawi" if country_iso3=="MWI"
		replace	country_name="Malaysia" if country_iso3=="MYS"
		replace	country_name="Maldives" if country_iso3=="MDV"
		replace	country_name="Mali" if country_iso3=="MLI"
		replace	country_name="Malta" if country_iso3=="MLT"
		replace	country_name="Marshall Islands" if country_iso3=="MHL"
		replace	country_name="Martinique" if country_iso3=="MTQ"
		replace	country_name="Mauritania" if country_iso3=="MRT"
		replace	country_name="Mauritius" if country_iso3=="MUS"
		replace	country_name="Mexico" if country_iso3=="MEX"
		replace	country_name="Micronesia" if country_iso3=="FSM"
		replace	country_name="Moldova" if country_iso3=="MDA"
		replace	country_name="Monaco" if country_iso3=="MCO"
		replace	country_name="Mongolia" if country_iso3=="MNG"
		replace	country_name="Montserrat" if country_iso3=="GBRMSR"
		replace	country_name="Montenegro" if country_iso3=="MNE"
		replace	country_name="Morocco" if country_iso3=="MAR"
		replace	country_name="Mozambique" if country_iso3=="MOZ"
		replace	country_name="Myanmar" if country_iso3=="MMR"
		replace	country_name="Namibia" if country_iso3=="NAM"
		replace	country_name="Nauru" if country_iso3=="NRU"
		replace	country_name="Nepal" if country_iso3=="NPL"
		replace	country_name="Netherlands" if country_iso3=="NLD"
		replace	country_name="Netherlands Antilles" if country_iso3=="NLDANT"
		replace	country_name="New Caledonia" if country_iso3=="FRANCL"
		replace	country_name="New Zealand" if country_iso3=="NZL"
		replace	country_name="Nicaragua" if country_iso3=="NIC"
		replace	country_name="Niger" if country_iso3=="NER"
		replace	country_name="Nigeria" if country_iso3=="NGA"
		replace	country_name="Niue" if country_iso3=="NZLNIU"
		replace	country_name="Norfolk Island" if country_iso3=="AUSNFK"
		replace	country_name="North Korea" if country_iso3=="PRK"
		replace	country_name="Northern Mariana Islands" if country_iso3=="MNP"
		replace	country_name="Norway" if country_iso3=="NOR"
		replace	country_name="Oman" if country_iso3=="OMN"
		replace	country_name="Pakistan" if country_iso3=="PAK"
		replace	country_name="Palau" if country_iso3=="PLW"
		replace	country_name="Occupied Palestinian Territory" if country_iso3=="PSE"
		replace	country_name="Gaza" if country_iso3=="PSEGZA"
		replace	country_name="Panama" if country_iso3=="PAN"
		replace	country_name="Papua New Guinea" if country_iso3=="PNG"
		replace	country_name="Paraguay" if country_iso3=="PRY"
		replace	country_name="Peru" if country_iso3=="PER"
		replace	country_name="Philippines" if country_iso3=="PHL"
		replace	country_name="Pitcairn" if country_iso3=="GBRPCN"
		replace	country_name="Poland" if country_iso3=="POL"
		replace	country_name="Portugal" if country_iso3=="PRT"
		replace	country_name="Puerto Rico" if country_iso3=="USAPRI"
		replace	country_name="Qatar" if country_iso3=="QAT"
		replace	country_name="South Africa" if country_iso3=="ZAF"
		replace	country_name="Romania" if country_iso3=="ROU"
		replace	country_name="Russia" if country_iso3=="RUS"
		replace	country_name="Rwanda" if country_iso3=="RWA"
		replace	country_name="Saint Helena" if country_iso3=="GBRSHN"
		replace	country_name="Saint Lucia" if country_iso3=="LCA"
		replace	country_name="Saint Kitts and Nevis" if country_iso3=="KNA"
		replace	country_name="Saint Martin (French part)" if country_iso3=="MAF"
		replace	country_name="Saint Vincent and the Grenadines" if country_iso3=="VCT"
		replace	country_name="Samoa" if country_iso3=="WSM"
		replace	country_name="San Marino" if country_iso3=="SMR"
		replace	country_name="Sao Tome and Principe" if country_iso3=="STP"
		replace	country_name="Saudi Arabia" if country_iso3=="SAU"
		replace	country_name="Senegal" if country_iso3=="SEN"
		replace	country_name="Serbia" if country_iso3=="SRB"
		replace	country_name="Seychelles" if country_iso3=="SYC"
		replace	country_name="Sierra Leone" if country_iso3=="SLE"
		replace	country_name="Singapore" if country_iso3=="SGP"
		replace	country_name="Sint Maarten" if country_iso3=="SXM"
		replace	country_name="Slovakia" if country_iso3=="SVK"
		replace	country_name="Slovenia" if country_iso3=="SVN"
		replace	country_name="Solomon Islands" if country_iso3=="SLB"
		replace	country_name="Somalia" if country_iso3=="SOM"
		replace	country_name="South Korea" if country_iso3=="KOR"
		replace	country_name="South Sudan" if country_iso3=="SSD"
		replace	country_name="Spain" if country_iso3=="ESP"
		replace	country_name="Sri Lanka" if country_iso3=="LKA"
		replace	country_name="Sudan" if country_iso3=="SDN"
		replace	country_name="Suriname" if country_iso3=="SUR"
		replace	country_name="Swaziland" if country_iso3=="SWZ"
		replace	country_name="Sweden" if country_iso3=="SWE"
		replace	country_name="Switzerland" if country_iso3=="CHE"
		replace	country_name="Syria" if country_iso3=="SYR"
		replace	country_name="Taiwan" if country_iso3=="TWN"
		replace	country_name="Tajikistan" if country_iso3=="TJK"
		replace	country_name="Tanzania" if country_iso3=="TZA"
		replace	country_name="Thailand" if country_iso3=="THA"
		replace	country_name="East Timor" if country_iso3=="TMP"
		replace	country_name="Togo" if country_iso3=="TGO"
		replace	country_name="Tokelau" if country_iso3=="NZLTKL"
		replace	country_name="Tonga" if country_iso3=="TON"
		replace	country_name="Trinidad and Tobago" if country_iso3=="TTO"
		replace	country_name="Tunisia" if country_iso3=="TUN"
		replace	country_name="Turkey" if country_iso3=="TUR"
		replace	country_name="Turkmenistan" if country_iso3=="TKM"
		replace	country_name="Turks and Caicos Islands" if country_iso3=="TCA"
		replace	country_name="Tuvalu" if country_iso3=="TUV"
		replace	country_name="Uganda" if country_iso3=="UGA"
		replace	country_name="Ukraine" if country_iso3=="UKR"
		replace	country_name="United Arab Emirates" if country_iso3=="ARE"
		replace	country_name="Uruguay" if country_iso3=="URY"
		replace	country_name="United States" if country_iso3=="USA"
		replace	country_name="United States Virgin Islands" if country_iso3=="USAVIR"
		replace	country_name="Uzbekistan" if country_iso3=="UZB"
		replace	country_name="Vanuatu" if country_iso3=="VUT"
		replace	country_name="Venezuela" if country_iso3=="VEN"
		replace	country_name="Vietnam" if country_iso3=="VNM"
		replace	country_name="Wallis and Futuna Islands" if country_iso3=="FRNWLF"
		replace	country_name="Western Sahara" if country_iso3=="ESH"
		replace	country_name="Yemen" if country_iso3=="YEM"
		replace	country_name="Zambia" if country_iso3=="ZMB"
		replace	country_name="Zimbabwe" if country_iso3=="ZWE"
		replace	country_name="British Indian Ocean Territory" if country_iso3=="IOT"
		replace	country_name="Christmas Island" if country_iso3=="CXR"
		replace	country_name="Cocos Islands" if country_iso3=="CCK"		
	la var country_name "country name"
		
	end
